"""avance 1: usuarios, sesiones, planes y suscripciones

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 12:46:34.620577
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes',
    sa.Column('id_plan', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('precio_mensual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento_anual_pct', sa.SmallInteger(), nullable=False),
    sa.Column('almacenamiento_gb', sa.Integer(), nullable=False),
    sa.Column('vigencia_dias', sa.Integer(), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('almacenamiento_gb > 0', name='ck_planes_almacenamiento'),
    sa.CheckConstraint('descuento_anual_pct BETWEEN 0 AND 100', name='ck_planes_descuento'),
    sa.CheckConstraint('precio_mensual >= 0', name='ck_planes_precio'),
    sa.CheckConstraint('vigencia_dias > 0', name='ck_planes_vigencia'),
    sa.PrimaryKeyConstraint('id_plan'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.SmallInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('plan_caracteristicas',
    sa.Column('id_caracteristica', sa.Uuid(), nullable=False),
    sa.Column('id_plan', sa.Uuid(), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_plan'], ['planes.id_plan'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_caracteristica')
    )
    op.create_index(op.f('ix_plan_caracteristicas_id_plan'), 'plan_caracteristicas', ['id_plan'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('id_rol', sa.SmallInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('correo_verificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acepto_terminos_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('almacenamiento_usado_bytes', sa.BigInteger(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente','activo','suspendido')", name='ck_usuarios_estado'),
    sa.CheckConstraint('almacenamiento_usado_bytes >= 0', name='ck_usuarios_uso_positivo'),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_table('sesiones',
    sa.Column('id_sesion', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocada_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sesion'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index(op.f('ix_sesiones_id_usuario'), 'sesiones', ['id_usuario'], unique=False)
    op.create_table('suscripciones',
    sa.Column('id_suscripcion', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('id_plan', sa.Uuid(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('periodicidad', sa.String(length=10), nullable=False),
    sa.Column('precio_contratado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('renovacion_automatica', sa.Boolean(), nullable=False),
    sa.Column('cancelada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('activa','vencida','cancelada')", name='ck_suscripciones_estado'),
    sa.CheckConstraint("periodicidad IN ('mensual','anual')", name='ck_suscripciones_periodicidad'),
    sa.CheckConstraint('fecha_fin > fecha_inicio', name='ck_suscripciones_fechas'),
    sa.ForeignKeyConstraint(['id_plan'], ['planes.id_plan'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_suscripcion')
    )
    op.create_index(op.f('ix_suscripciones_id_plan'), 'suscripciones', ['id_plan'], unique=False)
    op.create_index(op.f('ix_suscripciones_id_usuario'), 'suscripciones', ['id_usuario'], unique=False)
    op.create_index('ux_suscripciones_una_activa', 'suscripciones', ['id_usuario'], unique=True, postgresql_where=sa.text("estado = 'activa'"), sqlite_where=sa.text("estado = 'activa'"))
    op.create_table('tokens_usuario',
    sa.Column('id_token', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('verificacion','recuperacion')", name='ck_tokens_tipo'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_token'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_tokens_usuario_id_usuario'), 'tokens_usuario', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_usuario_id_usuario'), table_name='tokens_usuario')
    op.drop_table('tokens_usuario')
    op.drop_index('ux_suscripciones_una_activa', table_name='suscripciones', postgresql_where=sa.text("estado = 'activa'"), sqlite_where=sa.text("estado = 'activa'"))
    op.drop_index(op.f('ix_suscripciones_id_usuario'), table_name='suscripciones')
    op.drop_index(op.f('ix_suscripciones_id_plan'), table_name='suscripciones')
    op.drop_table('suscripciones')
    op.drop_index(op.f('ix_sesiones_id_usuario'), table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_plan_caracteristicas_id_plan'), table_name='plan_caracteristicas')
    op.drop_table('plan_caracteristicas')
    op.drop_table('roles')
    op.drop_table('planes')
    # ### end Alembic commands ###
