"""avance 2: carpetas, archivos y pagos

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 18:11:29.859744
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpetas',
    sa.Column('id_carpeta', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('id_carpeta_padre', sa.Uuid(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_carpeta_padre'], ['carpetas.id_carpeta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_carpeta')
    )
    op.create_index(op.f('ix_carpetas_id_carpeta_padre'), 'carpetas', ['id_carpeta_padre'], unique=False)
    op.create_index(op.f('ix_carpetas_id_usuario'), 'carpetas', ['id_usuario'], unique=False)
    op.create_table('archivos',
    sa.Column('id_archivo', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('id_carpeta', sa.Uuid(), nullable=True),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('clave_objeto', sa.String(length=512), nullable=False),
    sa.Column('tipo_mime', sa.String(length=120), nullable=False),
    sa.Column('tamano_bytes', sa.BigInteger(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('tamano_bytes >= 0', name='ck_archivos_tamano'),
    sa.ForeignKeyConstraint(['id_carpeta'], ['carpetas.id_carpeta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_archivo'),
    sa.UniqueConstraint('clave_objeto')
    )
    op.create_index(op.f('ix_archivos_id_carpeta'), 'archivos', ['id_carpeta'], unique=False)
    op.create_index(op.f('ix_archivos_id_usuario'), 'archivos', ['id_usuario'], unique=False)
    op.create_table('pagos',
    sa.Column('id_pago', sa.Uuid(), nullable=False),
    sa.Column('id_suscripcion', sa.Uuid(), nullable=False),
    sa.Column('numero_comprobante', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_simulado', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente','aprobado','rechazado')", name='ck_pagos_estado'),
    sa.CheckConstraint('monto >= 0', name='ck_pagos_monto'),
    sa.ForeignKeyConstraint(['id_suscripcion'], ['suscripciones.id_suscripcion'], ),
    sa.PrimaryKeyConstraint('id_pago'),
    sa.UniqueConstraint('numero_comprobante')
    )
    op.create_index(op.f('ix_pagos_id_suscripcion'), 'pagos', ['id_suscripcion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_id_suscripcion'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_archivos_id_usuario'), table_name='archivos')
    op.drop_index(op.f('ix_archivos_id_carpeta'), table_name='archivos')
    op.drop_table('archivos')
    op.drop_index(op.f('ix_carpetas_id_usuario'), table_name='carpetas')
    op.drop_index(op.f('ix_carpetas_id_carpeta_padre'), table_name='carpetas')
    op.drop_table('carpetas')
    # ### end Alembic commands ###
