"""archivos y carpetas

Revision ID: ca3c8c7188b1
Revises: 0001
Create Date: 2026-10-07 04:23:55.429300
"""

from alembic import op
import sqlalchemy as sa


revision = 'ca3c8c7188b1'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpetas',
    sa.Column('id_carpeta', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('id_carpeta_padre', sa.Uuid(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_carpeta_padre'], ['carpetas.id_carpeta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_carpeta')
    )
    op.create_index(op.f('ix_carpetas_id_carpeta_padre'), 'carpetas', ['id_carpeta_padre'], unique=False)
    op.create_index(op.f('ix_carpetas_id_usuario'), 'carpetas', ['id_usuario'], unique=False)

    op.create_table('archivos',
    sa.Column('id_archivo', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('id_carpeta', sa.Uuid(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('tamaño_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('clave_objeto', sa.String(length=500), nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('eliminado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_carpeta'], ['carpetas.id_carpeta'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_archivo'),
    sa.UniqueConstraint('clave_objeto')
    )
    op.create_index(op.f('ix_archivos_id_carpeta'), 'archivos', ['id_carpeta'], unique=False)
    op.create_index(op.f('ix_archivos_id_usuario'), 'archivos', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archivos_id_usuario'), table_name='archivos')
    op.drop_index(op.f('ix_archivos_id_carpeta'), table_name='archivos')
    op.drop_table('archivos')
    op.drop_index(op.f('ix_carpetas_id_usuario'), table_name='carpetas')
    op.drop_index(op.f('ix_carpetas_id_carpeta_padre'), table_name='carpetas')
    op.drop_table('carpetas')
    # ### end Alembic commands ###
